version: 0.1

phases:
  build:
    commands:
      - mvn clean package
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  type: zip
  files:
    - serverless-peer-reward/**/*
  discard-paths: no
